apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"myapp","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"myapp"}},"template":{"metadata":{"labels":{"app":"myapp"}},"spec":{"containers":[{"image":"amigoscode/kubernetes:springboot-react-fullstack-v1","name":"myapp","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"}}}]}}}}
  creationTimestamp: "2022-10-11T01:07:16Z"
  generation: 1
  name: myapp
  namespace: default
  resourceVersion: "1109"
  uid: 7f26d240-0e16-4b26-8fa4-0f7be3af3a91
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: amigoscode/kubernetes:springboot-react-fullstack-v1
        imagePullPolicy: IfNotPresent
        name: myapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-10-11T01:08:15Z"
    lastUpdateTime: "2022-10-11T01:08:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-10-11T01:07:16Z"
    lastUpdateTime: "2022-10-11T01:08:15Z"
    message: ReplicaSet "myapp-859b4cd455" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
